# other reference: https://github.com/mvdan/github-actions-golang
name: build

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  test:

    strategy:
      matrix:
        go:
        - '1.14.8'
        - '1.15.1'
    runs-on: ubuntu-18.04
    container:
      image: golang:${{ matrix.go }}-alpine3.12

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: |
        go test -v -race $(go list ./... | grep -v /vendor/) -coverprofile=coverage.txt
      shell: bash
